# This file contains the basic configuration to create your own jekyll site using the BB theme.

# Basic Settings
title: BB Jekyll Theme
email: your-email@domain.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aqwantonio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: aqwantonio # your github username
theme: just-the-docs
lang: ru-RU

# Aux links for the upper right navigation
aux_links:
  "Просмотреть на GitHub":
    - "https://github.com/your-username/bb-source"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Whether to show the "Edit this page on GitHub" link
gh_edit_link: true
gh_edit_link_text: "Редактировать на GitHub"
gh_edit_repository: "https://github.com/your-username/bb-source"
gh_edit_branch: main
gh_edit_view_mode: "tree"

# Footer content
footer_content: "Copyright &copy; 2024. База знаний по бодибилдингу и фитнесу для Перми."

# Color scheme currently only supports "light" (default) and "dark"
color_scheme: light

# Enable search
search_enabled: true
search_tokenizer_separator: /[\s\-\.]+/

# Collections
collections:
  vidy-uprazhneniy:
    output: true
    permalink: /:collection/:path/
  vse-o-fitnese:
    output: true
    permalink: /:collection/:path/
  o-bodibildinge:
    output: true
    permalink: /:collection/:path/
  pitanie-i-dieta:
    output: true
    permalink: /:collection/:path/
  programmy-trenirovok:
    output: true
    permalink: /:collection/:path/
  farmakologiya:
    output: true
    permalink: /:collection/:path/
  fiziologiya:
    output: true
    permalink: /:collection/:path/
  pervaya-pomoshch-travmy:
    output: true
    permalink: /:collection/:path/ 